import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "next-themes";
import ThemeProvider from "@/theme/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/header";
// import { ThemeProvider } from "@/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black`}
      >
        <SidebarProvider>
          <ThemeProvider>
            <AppSidebar />
            {/* <main className="max-w-6xl mx-auto p-6 bg-white dark:bg-gray-900 text-black dark:text-white"> */}
            <main className="w-full bg-white dark:bg-gray-900 text-black dark:text-white">
              <Header />
              {children}
            </main>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
